// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"
	"notify-api/app/manager/push/enum"
	"notify-api/db/ent/generate/device"
	"notify-api/db/ent/generate/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeviceCreate is the builder for creating a Device entity.
type DeviceCreate struct {
	config
	mutation *DeviceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (dc *DeviceCreate) SetCreatedAt(t time.Time) *DeviceCreate {
	dc.mutation.SetCreatedAt(t)
	return dc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dc *DeviceCreate) SetNillableCreatedAt(t *time.Time) *DeviceCreate {
	if t != nil {
		dc.SetCreatedAt(*t)
	}
	return dc
}

// SetUpdatedAt sets the "updated_at" field.
func (dc *DeviceCreate) SetUpdatedAt(t time.Time) *DeviceCreate {
	dc.mutation.SetUpdatedAt(t)
	return dc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (dc *DeviceCreate) SetNillableUpdatedAt(t *time.Time) *DeviceCreate {
	if t != nil {
		dc.SetUpdatedAt(*t)
	}
	return dc
}

// SetIdentifier sets the "identifier" field.
func (dc *DeviceCreate) SetIdentifier(s string) *DeviceCreate {
	dc.mutation.SetIdentifier(s)
	return dc
}

// SetChannel sets the "channel" field.
func (dc *DeviceCreate) SetChannel(e enum.Sender) *DeviceCreate {
	dc.mutation.SetChannel(e)
	return dc
}

// SetChannelMeta sets the "channelMeta" field.
func (dc *DeviceCreate) SetChannelMeta(s string) *DeviceCreate {
	dc.mutation.SetChannelMeta(s)
	return dc
}

// SetChannelToken sets the "channelToken" field.
func (dc *DeviceCreate) SetChannelToken(s string) *DeviceCreate {
	dc.mutation.SetChannelToken(s)
	return dc
}

// SetDeviceName sets the "deviceName" field.
func (dc *DeviceCreate) SetDeviceName(s string) *DeviceCreate {
	dc.mutation.SetDeviceName(s)
	return dc
}

// SetDeviceMeta sets the "deviceMeta" field.
func (dc *DeviceCreate) SetDeviceMeta(s string) *DeviceCreate {
	dc.mutation.SetDeviceMeta(s)
	return dc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (dc *DeviceCreate) SetUserID(id int) *DeviceCreate {
	dc.mutation.SetUserID(id)
	return dc
}

// SetUser sets the "user" edge to the User entity.
func (dc *DeviceCreate) SetUser(u *User) *DeviceCreate {
	return dc.SetUserID(u.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (dc *DeviceCreate) Mutation() *DeviceMutation {
	return dc.mutation
}

// Save creates the Device in the database.
func (dc *DeviceCreate) Save(ctx context.Context) (*Device, error) {
	dc.defaults()
	return withHooks[*Device, DeviceMutation](ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DeviceCreate) SaveX(ctx context.Context) *Device {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DeviceCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DeviceCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dc *DeviceCreate) defaults() {
	if _, ok := dc.mutation.CreatedAt(); !ok {
		v := device.DefaultCreatedAt()
		dc.mutation.SetCreatedAt(v)
	}
	if _, ok := dc.mutation.UpdatedAt(); !ok {
		v := device.DefaultUpdatedAt()
		dc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DeviceCreate) check() error {
	if _, ok := dc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`generate: missing required field "Device.created_at"`)}
	}
	if _, ok := dc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`generate: missing required field "Device.updated_at"`)}
	}
	if _, ok := dc.mutation.Identifier(); !ok {
		return &ValidationError{Name: "identifier", err: errors.New(`generate: missing required field "Device.identifier"`)}
	}
	if _, ok := dc.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`generate: missing required field "Device.channel"`)}
	}
	if _, ok := dc.mutation.ChannelMeta(); !ok {
		return &ValidationError{Name: "channelMeta", err: errors.New(`generate: missing required field "Device.channelMeta"`)}
	}
	if _, ok := dc.mutation.ChannelToken(); !ok {
		return &ValidationError{Name: "channelToken", err: errors.New(`generate: missing required field "Device.channelToken"`)}
	}
	if _, ok := dc.mutation.DeviceName(); !ok {
		return &ValidationError{Name: "deviceName", err: errors.New(`generate: missing required field "Device.deviceName"`)}
	}
	if _, ok := dc.mutation.DeviceMeta(); !ok {
		return &ValidationError{Name: "deviceMeta", err: errors.New(`generate: missing required field "Device.deviceMeta"`)}
	}
	if _, ok := dc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`generate: missing required edge "Device.user"`)}
	}
	return nil
}

func (dc *DeviceCreate) sqlSave(ctx context.Context) (*Device, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DeviceCreate) createSpec() (*Device, *sqlgraph.CreateSpec) {
	var (
		_node = &Device{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(device.Table, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	)
	_spec.OnConflict = dc.conflict
	if value, ok := dc.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dc.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := dc.mutation.Identifier(); ok {
		_spec.SetField(device.FieldIdentifier, field.TypeString, value)
		_node.Identifier = value
	}
	if value, ok := dc.mutation.Channel(); ok {
		_spec.SetField(device.FieldChannel, field.TypeString, value)
		_node.Channel = value
	}
	if value, ok := dc.mutation.ChannelMeta(); ok {
		_spec.SetField(device.FieldChannelMeta, field.TypeString, value)
		_node.ChannelMeta = value
	}
	if value, ok := dc.mutation.ChannelToken(); ok {
		_spec.SetField(device.FieldChannelToken, field.TypeString, value)
		_node.ChannelToken = value
	}
	if value, ok := dc.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := dc.mutation.DeviceMeta(); ok {
		_spec.SetField(device.FieldDeviceMeta, field.TypeString, value)
		_node.DeviceMeta = value
	}
	if nodes := dc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_devices = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Device.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (dc *DeviceCreate) OnConflict(opts ...sql.ConflictOption) *DeviceUpsertOne {
	dc.conflict = opts
	return &DeviceUpsertOne{
		create: dc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dc *DeviceCreate) OnConflictColumns(columns ...string) *DeviceUpsertOne {
	dc.conflict = append(dc.conflict, sql.ConflictColumns(columns...))
	return &DeviceUpsertOne{
		create: dc,
	}
}

type (
	// DeviceUpsertOne is the builder for "upsert"-ing
	//  one Device node.
	DeviceUpsertOne struct {
		create *DeviceCreate
	}

	// DeviceUpsert is the "OnConflict" setter.
	DeviceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceUpsert) SetUpdatedAt(v time.Time) *DeviceUpsert {
	u.Set(device.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateUpdatedAt() *DeviceUpsert {
	u.SetExcluded(device.FieldUpdatedAt)
	return u
}

// SetIdentifier sets the "identifier" field.
func (u *DeviceUpsert) SetIdentifier(v string) *DeviceUpsert {
	u.Set(device.FieldIdentifier, v)
	return u
}

// UpdateIdentifier sets the "identifier" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateIdentifier() *DeviceUpsert {
	u.SetExcluded(device.FieldIdentifier)
	return u
}

// SetChannel sets the "channel" field.
func (u *DeviceUpsert) SetChannel(v enum.Sender) *DeviceUpsert {
	u.Set(device.FieldChannel, v)
	return u
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateChannel() *DeviceUpsert {
	u.SetExcluded(device.FieldChannel)
	return u
}

// SetChannelMeta sets the "channelMeta" field.
func (u *DeviceUpsert) SetChannelMeta(v string) *DeviceUpsert {
	u.Set(device.FieldChannelMeta, v)
	return u
}

// UpdateChannelMeta sets the "channelMeta" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateChannelMeta() *DeviceUpsert {
	u.SetExcluded(device.FieldChannelMeta)
	return u
}

// SetChannelToken sets the "channelToken" field.
func (u *DeviceUpsert) SetChannelToken(v string) *DeviceUpsert {
	u.Set(device.FieldChannelToken, v)
	return u
}

// UpdateChannelToken sets the "channelToken" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateChannelToken() *DeviceUpsert {
	u.SetExcluded(device.FieldChannelToken)
	return u
}

// SetDeviceName sets the "deviceName" field.
func (u *DeviceUpsert) SetDeviceName(v string) *DeviceUpsert {
	u.Set(device.FieldDeviceName, v)
	return u
}

// UpdateDeviceName sets the "deviceName" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateDeviceName() *DeviceUpsert {
	u.SetExcluded(device.FieldDeviceName)
	return u
}

// SetDeviceMeta sets the "deviceMeta" field.
func (u *DeviceUpsert) SetDeviceMeta(v string) *DeviceUpsert {
	u.Set(device.FieldDeviceMeta, v)
	return u
}

// UpdateDeviceMeta sets the "deviceMeta" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateDeviceMeta() *DeviceUpsert {
	u.SetExcluded(device.FieldDeviceMeta)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeviceUpsertOne) UpdateNewValues() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(device.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Device.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeviceUpsertOne) Ignore() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceUpsertOne) DoNothing() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceCreate.OnConflict
// documentation for more info.
func (u *DeviceUpsertOne) Update(set func(*DeviceUpsert)) *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceUpsertOne) SetUpdatedAt(v time.Time) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateUpdatedAt() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetIdentifier sets the "identifier" field.
func (u *DeviceUpsertOne) SetIdentifier(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetIdentifier(v)
	})
}

// UpdateIdentifier sets the "identifier" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateIdentifier() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateIdentifier()
	})
}

// SetChannel sets the "channel" field.
func (u *DeviceUpsertOne) SetChannel(v enum.Sender) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateChannel() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateChannel()
	})
}

// SetChannelMeta sets the "channelMeta" field.
func (u *DeviceUpsertOne) SetChannelMeta(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetChannelMeta(v)
	})
}

// UpdateChannelMeta sets the "channelMeta" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateChannelMeta() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateChannelMeta()
	})
}

// SetChannelToken sets the "channelToken" field.
func (u *DeviceUpsertOne) SetChannelToken(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetChannelToken(v)
	})
}

// UpdateChannelToken sets the "channelToken" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateChannelToken() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateChannelToken()
	})
}

// SetDeviceName sets the "deviceName" field.
func (u *DeviceUpsertOne) SetDeviceName(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "deviceName" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateDeviceName() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceName()
	})
}

// SetDeviceMeta sets the "deviceMeta" field.
func (u *DeviceUpsertOne) SetDeviceMeta(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceMeta(v)
	})
}

// UpdateDeviceMeta sets the "deviceMeta" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateDeviceMeta() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceMeta()
	})
}

// Exec executes the query.
func (u *DeviceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for DeviceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeviceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeviceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeviceCreateBulk is the builder for creating many Device entities in bulk.
type DeviceCreateBulk struct {
	config
	builders []*DeviceCreate
	conflict []sql.ConflictOption
}

// Save creates the Device entities in the database.
func (dcb *DeviceCreateBulk) Save(ctx context.Context) ([]*Device, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Device, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = dcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DeviceCreateBulk) SaveX(ctx context.Context) []*Device {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DeviceCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Device.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (dcb *DeviceCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeviceUpsertBulk {
	dcb.conflict = opts
	return &DeviceUpsertBulk{
		create: dcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dcb *DeviceCreateBulk) OnConflictColumns(columns ...string) *DeviceUpsertBulk {
	dcb.conflict = append(dcb.conflict, sql.ConflictColumns(columns...))
	return &DeviceUpsertBulk{
		create: dcb,
	}
}

// DeviceUpsertBulk is the builder for "upsert"-ing
// a bulk of Device nodes.
type DeviceUpsertBulk struct {
	create *DeviceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeviceUpsertBulk) UpdateNewValues() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(device.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeviceUpsertBulk) Ignore() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceUpsertBulk) DoNothing() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceCreateBulk.OnConflict
// documentation for more info.
func (u *DeviceUpsertBulk) Update(set func(*DeviceUpsert)) *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceUpsertBulk) SetUpdatedAt(v time.Time) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateUpdatedAt() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetIdentifier sets the "identifier" field.
func (u *DeviceUpsertBulk) SetIdentifier(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetIdentifier(v)
	})
}

// UpdateIdentifier sets the "identifier" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateIdentifier() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateIdentifier()
	})
}

// SetChannel sets the "channel" field.
func (u *DeviceUpsertBulk) SetChannel(v enum.Sender) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateChannel() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateChannel()
	})
}

// SetChannelMeta sets the "channelMeta" field.
func (u *DeviceUpsertBulk) SetChannelMeta(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetChannelMeta(v)
	})
}

// UpdateChannelMeta sets the "channelMeta" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateChannelMeta() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateChannelMeta()
	})
}

// SetChannelToken sets the "channelToken" field.
func (u *DeviceUpsertBulk) SetChannelToken(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetChannelToken(v)
	})
}

// UpdateChannelToken sets the "channelToken" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateChannelToken() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateChannelToken()
	})
}

// SetDeviceName sets the "deviceName" field.
func (u *DeviceUpsertBulk) SetDeviceName(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "deviceName" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateDeviceName() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceName()
	})
}

// SetDeviceMeta sets the "deviceMeta" field.
func (u *DeviceUpsertBulk) SetDeviceMeta(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceMeta(v)
	})
}

// UpdateDeviceMeta sets the "deviceMeta" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateDeviceMeta() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceMeta()
	})
}

// Exec executes the query.
func (u *DeviceUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("generate: OnConflict was set for builder %d. Set it on the DeviceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for DeviceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
