// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"
	"notify-api/ent/generate/device"
	"notify-api/ent/generate/predicate"
	"notify-api/ent/generate/user"
	"notify-api/push/enum"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (du *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetUpdatedAt sets the "updated_at" field.
func (du *DeviceUpdate) SetUpdatedAt(t time.Time) *DeviceUpdate {
	du.mutation.SetUpdatedAt(t)
	return du
}

// SetIdentifier sets the "identifier" field.
func (du *DeviceUpdate) SetIdentifier(s string) *DeviceUpdate {
	du.mutation.SetIdentifier(s)
	return du
}

// SetChannel sets the "channel" field.
func (du *DeviceUpdate) SetChannel(e enum.Sender) *DeviceUpdate {
	du.mutation.SetChannel(e)
	return du
}

// SetChannelMeta sets the "channelMeta" field.
func (du *DeviceUpdate) SetChannelMeta(s string) *DeviceUpdate {
	du.mutation.SetChannelMeta(s)
	return du
}

// SetChannelToken sets the "channelToken" field.
func (du *DeviceUpdate) SetChannelToken(s string) *DeviceUpdate {
	du.mutation.SetChannelToken(s)
	return du
}

// SetDeviceName sets the "deviceName" field.
func (du *DeviceUpdate) SetDeviceName(s string) *DeviceUpdate {
	du.mutation.SetDeviceName(s)
	return du
}

// SetDeviceMeta sets the "deviceMeta" field.
func (du *DeviceUpdate) SetDeviceMeta(s string) *DeviceUpdate {
	du.mutation.SetDeviceMeta(s)
	return du
}

// SetUserID sets the "user" edge to the User entity by ID.
func (du *DeviceUpdate) SetUserID(id int) *DeviceUpdate {
	du.mutation.SetUserID(id)
	return du
}

// SetUser sets the "user" edge to the User entity.
func (du *DeviceUpdate) SetUser(u *User) *DeviceUpdate {
	return du.SetUserID(u.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (du *DeviceUpdate) Mutation() *DeviceMutation {
	return du.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (du *DeviceUpdate) ClearUser() *DeviceUpdate {
	du.mutation.ClearUser()
	return du
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DeviceUpdate) Save(ctx context.Context) (int, error) {
	du.defaults()
	return withHooks[int, DeviceMutation](ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DeviceUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (du *DeviceUpdate) defaults() {
	if _, ok := du.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		du.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DeviceUpdate) check() error {
	if _, ok := du.mutation.UserID(); du.mutation.UserCleared() && !ok {
		return errors.New(`generate: clearing a required unique edge "Device.user"`)
	}
	return nil
}

func (du *DeviceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   device.Table,
			Columns: device.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: device.FieldID,
			},
		},
	}
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := du.mutation.Identifier(); ok {
		_spec.SetField(device.FieldIdentifier, field.TypeString, value)
	}
	if value, ok := du.mutation.Channel(); ok {
		_spec.SetField(device.FieldChannel, field.TypeString, value)
	}
	if value, ok := du.mutation.ChannelMeta(); ok {
		_spec.SetField(device.FieldChannelMeta, field.TypeString, value)
	}
	if value, ok := du.mutation.ChannelToken(); ok {
		_spec.SetField(device.FieldChannelToken, field.TypeString, value)
	}
	if value, ok := du.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := du.mutation.DeviceMeta(); ok {
		_spec.SetField(device.FieldDeviceMeta, field.TypeString, value)
	}
	if du.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (duo *DeviceUpdateOne) SetUpdatedAt(t time.Time) *DeviceUpdateOne {
	duo.mutation.SetUpdatedAt(t)
	return duo
}

// SetIdentifier sets the "identifier" field.
func (duo *DeviceUpdateOne) SetIdentifier(s string) *DeviceUpdateOne {
	duo.mutation.SetIdentifier(s)
	return duo
}

// SetChannel sets the "channel" field.
func (duo *DeviceUpdateOne) SetChannel(e enum.Sender) *DeviceUpdateOne {
	duo.mutation.SetChannel(e)
	return duo
}

// SetChannelMeta sets the "channelMeta" field.
func (duo *DeviceUpdateOne) SetChannelMeta(s string) *DeviceUpdateOne {
	duo.mutation.SetChannelMeta(s)
	return duo
}

// SetChannelToken sets the "channelToken" field.
func (duo *DeviceUpdateOne) SetChannelToken(s string) *DeviceUpdateOne {
	duo.mutation.SetChannelToken(s)
	return duo
}

// SetDeviceName sets the "deviceName" field.
func (duo *DeviceUpdateOne) SetDeviceName(s string) *DeviceUpdateOne {
	duo.mutation.SetDeviceName(s)
	return duo
}

// SetDeviceMeta sets the "deviceMeta" field.
func (duo *DeviceUpdateOne) SetDeviceMeta(s string) *DeviceUpdateOne {
	duo.mutation.SetDeviceMeta(s)
	return duo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (duo *DeviceUpdateOne) SetUserID(id int) *DeviceUpdateOne {
	duo.mutation.SetUserID(id)
	return duo
}

// SetUser sets the "user" edge to the User entity.
func (duo *DeviceUpdateOne) SetUser(u *User) *DeviceUpdateOne {
	return duo.SetUserID(u.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (duo *DeviceUpdateOne) Mutation() *DeviceMutation {
	return duo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (duo *DeviceUpdateOne) ClearUser() *DeviceUpdateOne {
	duo.mutation.ClearUser()
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Device entity.
func (duo *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	duo.defaults()
	return withHooks[*Device, DeviceMutation](ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (duo *DeviceUpdateOne) defaults() {
	if _, ok := duo.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		duo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DeviceUpdateOne) check() error {
	if _, ok := duo.mutation.UserID(); duo.mutation.UserCleared() && !ok {
		return errors.New(`generate: clearing a required unique edge "Device.user"`)
	}
	return nil
}

func (duo *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   device.Table,
			Columns: device.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: device.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`generate: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("generate: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := duo.mutation.Identifier(); ok {
		_spec.SetField(device.FieldIdentifier, field.TypeString, value)
	}
	if value, ok := duo.mutation.Channel(); ok {
		_spec.SetField(device.FieldChannel, field.TypeString, value)
	}
	if value, ok := duo.mutation.ChannelMeta(); ok {
		_spec.SetField(device.FieldChannelMeta, field.TypeString, value)
	}
	if value, ok := duo.mutation.ChannelToken(); ok {
		_spec.SetField(device.FieldChannelToken, field.TypeString, value)
	}
	if value, ok := duo.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := duo.mutation.DeviceMeta(); ok {
		_spec.SetField(device.FieldDeviceMeta, field.TypeString, value)
	}
	if duo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Device{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
