name: Pull Request CI

on:
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  tests:
    needs: [ lint ]
    uses: ./.github/workflows/tests.yml

  build:
    needs: [ tests ]
    uses: ./.github/workflows/build.yml

  sdk-tests:
    needs: [ build ]
    uses: ./.github/workflows/sdk-tests.yml

  docker-build:
    name: Build Docker image (amd64 and arm64)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Prefetch dependencies
        run: go mod vendor && make frontend

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image without publishing
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            PREFETCHED=true
